### PR TITLE
Fix spelling in rig authorisation

### PR DESCRIPTION
**Pull request by johnathan99j**

### CODE REVIEW

**Comment by johnathan99j** [comment]
"testRigCreate (RIGS.test_functional.EventTest) ... FAIL"
Wasn't me, @davidtaylorhq

**Comment by johnathan99j** [comment]
Now it seems to keep timing out, odd.

**Comment by davidtaylorhq** [comment]
This is quite possibly the most boring PR so far, well done 😛

Anyway, restarted the tests and all is fine - travis must've been having a bad day. Thanks :)

**Comment by johnathan99j** [comment]
Yer but I couldn't just commit it straight to master as I don't have access (rightly so)

**Pull request merged**
