### PR TITLE
Heroku Staging Setup

### PR DESCRIPTION
**Pull request by davidtaylorhq**

### CODE REVIEW

**Comment by davidtaylorhq** [comment]
Will work on event sample data tomorrow evening

**Comment by tomtom5152** [comment]
Looks really good, but you appear to have made coveralls quite angry with this by not running the command as part of the tests. If that could be a thing it would be amazing!

**Comment by davidtaylorhq** [comment]
Yeah can definitely do that. I'm thinking that just running it and checking for no exceptions should be enough?

**Comment by tomtom5152** [comment]
Sounds good, also check there is more data in the database after it's finished and that some atomiticity hasn't screwed you over. On that note, can I suggest that the whole command is wrapped in a `with atomic:` statement just to be on the safe side in case there is an issue, at least in the critical section. More than happy to do this if you want me to.

**Comment by davidtaylorhq** [comment]
@tomtom5152 Yeah that sounds good - I'll sort it tomorrow. Also need to add the appropriate 

with reversion.make_revision: 

statements

**Comment by davidtaylorhq** [comment]
@davidtaylorhq Equally if you want to do it then feel free ;)

**Comment by davidtaylorhq** [comment]
@tomtom5152 ready for review methinks

**Comment by tomtom5152** [comment]
Are we sure that app.json isn't going to screw the main deploy over?

**Comment by davidtaylorhq** [comment]
@tomtom5152 Well app.json is already in master, so I'm gonna go with no ;)

**Comment by tomtom5152** [comment]
You have however added new env vars, which feels like it is going to deploy with those options.

**Comment by davidtaylorhq** [comment]
@tomtom5152 Well my original understanding was that this app.json was only used for the review apps. Having just looked, it can also be used for standard deploys... So I'm not 100% sure. If there's nothing on heroku's website about it then it might be worth asking them how to distinguish review apps from production

**Comment by tomtom5152** [comment]
Having thought about it more, it looks like app.json just provides a default value, which can be overwritten in the main app env vars. I'm working on this assumption, and going to deploy after setting the env var and hope for the best. Naturally I'll take a backup first just in case.

**Comment by davidtaylorhq** [comment]
@tomtom5152 Sounds good. Certainly the env variables are only set when you first create a pull request (subsequent commits to the branch don't cause the env variables to be reset). So basically as long as we don't destroy the production app and start again we'll be fine

**Pull request merged**
