### PR TITLE
Allow authentication using Discourse forum

### PR DESCRIPTION
**Pull request by davidtaylorhq**

### CODE REVIEW

**Comment by davidtaylorhq** [comment]
Well, the tests fail because I disabled Django registration, so to be expected

**Comment by tomtom5152** [comment]
Haven't checked any logic, but it all looks good. My main concern is it desperately needs tests, to the point where I almost feel the Discourse module should be a separate package that can be tested independently, then integrated into the RIGS properly. Also has the advantage of making it a standalone library that others can use.

Currently not happy for this to be merged without any tests.

**Comment by davidtaylorhq** [comment]
The more I think about it the more I agree with you.
I'm also now disliking the dependency on the external social-auth library - implementing the discourse auth is pretty easy with some basic cryptography libraries (see my mediawiki plugin) so I might try and write some middleware (or whatever it should be called) to do what we need in a more simple way. 
Would be nice if we can get this implemented before new members, so I'll try and get it done after my exam on Wednesday.

**Comment by davidtaylorhq** [comment]
Closing PR until I get around to re-writing

**Pull request closed without merging**
