### PR TITLE
[WIP] Update Python dependencies

### PR DESCRIPTION
**Pull request by tomtom5152**
Updated all python dependencies to the latest versions as per #216 

This was surprisingly easy, although revision required a slightly different import statement due to a change in the package structure.

This also includes a bonus wercker improvement to use postgres for tests again.

### CODE REVIEW

**Comment by davidtaylorhq** [comment]
Do I dare try and rebase this onto master? Or shall we just start again @tomtom5152?

**Comment by davidtaylorhq** [comment]
By some absolute miracle, this is working. All tests are passing and I've fixed the revision view. 

Now that's working, we should try and upgrade all the packages again, and try and get to Django 1.11. We should not update django-reversion above 1.10 for now, as that will cause the world of breakages. 

We have a number of deprecation notices in the logs, so we should fix those before trying to upgrade.

**Comment by davidtaylorhq** [comment]
Right... I've updated every single dependency with the exception of

- django-reversion (kept at 1.10.4), cos there are many breaking changes in 2.0
- selenium, cos it failed at communicating with firefox when I updated it, and I wanna move to chrome testing at some point anyway

Automated tests are all passing, YAY! I've pressed many buttons and it seems to be working.

Before we make this live (which we should do ASAP), would be good to get some users prodding it and trying to break it. Paging @nhyty @samozzy @rbrisk @tomtom5152 @wjdp

https://pyrigs-pr-217.herokuapp.com

Then I suggest that we leave it live for a few weeks before moving to python 3, which should hopefully be pretty painless now that we're up-to-date

**Comment by davidtaylorhq** [comment]
I think this is ready to merge, pending review from @tomtom5152  (who apparently I can't request a review from since you made the PR)

**Comment by tomtom5152** [comment]
@davidtaylorhq If you want this reviewing writing the next month your probably best finding somebody else to have a look, I really don't have time now

**Comment by davidtaylorhq** [comment]
Fair enough, I'm tempted to just go for the try it and see what happens approach. We can always roll back.

**Comment by davidtaylorhq** [comment]
Right then, let's see what happens

**Pull request merged**
