### PR TITLE
Search

### PR DESCRIPTION
**Pull request by davidtaylorhq**
Makes searching useful. @tomtom5152 I think you've already checked all the searching logic (see     f8afd8c) so only really need to check the changes I've made today

### CODE REVIEW

**Comment by davidtaylorhq** [comment]
@tomtom5152 BORING! But fair ;)

**Comment by FreneticScribbler** [comment]
[Search by name on RIGS](https://trello.com/c/CUQZcNkj/18-search-by-name-on-rigs)

**Comment by FreneticScribbler** [comment]
@mattysmith22 bump, needs review - not gonna rewrite RIGS tests to use the new style just yet..

**Comment by mattysmith22** [comment]
Looks good! I am just going to be picky and point out that it is not immediately logical to me how to swap between searching Rigs and Orgs / Venues. What I would recommend doing is one of the following:

* Put it in the already great help screen for search, simple solution but maybe not the most useful
* I know bootstrap select boxes can't be inlined with the item, but you could in essence build your own. Have it so that rather than redirecting, you use javascript so that each button swaps the text on a group to the clicked button, and changes what type of search is submitted when you click a second search button. This seems more natural to me, but is probably not worth implementing due to the amount of time it would take.
* By default you run the search as an event (if you press enter.) So simply change the current text of "🔎" to "Event 🔎" so that a user goes "Huh, I'm only searching events, what happens if I click on this?"

**Comment by FreneticScribbler** [comment]
> it is not immediately logical to me how to swap between searching Rigs and Orgs / Venues

Agreed - opportunity for a UX improvement in Bootstrap4 for sure. (allows easier impl of option two) I was initially in agreement with your option three but after some thought - clicking the button opens the dropdown, thereby revealing the path to the user. Anyone who's hitting enter rather than clicking buttons can probably figure out the meaning of the dropdown arrow symbol...

**Comment by mattysmith22** [comment]
Alright, in that case I'd do option 1 then, it's a very simple one and currently it makes it sound like it searches all of them at once, something we know it doesn't do!

**Comment by FreneticScribbler** [comment]
Option four it is... :laughing:

**Comment by FreneticScribbler** [comment]
Fingers crossed this doesn't choke on the production DB...

**Pull request merged**
