### PR TITLE
Reimplement rigboard page in a fully responsive manner

### PR DESCRIPTION
**Pull request by FreneticScribbler**
(cherry picked from commit b3939d84264faf1d2559a0257485b70df4a08930)

Requires refinement. Opening in order to get a review app going.

### CODE REVIEW

**Comment by FreneticScribbler** [comment]
I think this is now good to go if you're happy for me to merge it @nickw29 ? It's not perfect, and I bet *someone's* got a device that sits in a weird screen size spot, but it's better than the current sidescroll table by a mile!

**Review by nickw29 — APPROVED** [review]
Send it

**Comment by FreneticScribbler** [comment]
And so continues (barely) the long standing tradition of RIGS development during NAT panto 😆

**Comment by nickw29** [comment]
Screenshot_20231217-184605
Small issue on Chrome on android

**Comment by FreneticScribbler** [comment]
Works on my device! Maybe I'm the one with a weird screen size, lol.

How wide is your screen?

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by nickw29** [comment]
I've gone back to a phone with a normal sized screen, 20:9 - 2400x1080 - 6.4"

Edit: Phone is a Pixel 6

**Comment by jerbzz** [comment]
FYI this is what it looks like on my iPhone 14 Pro Max (1284px × 2778px, 430px × 932px viewport, CSS Pixel Ratio of 3)

image

image

**Comment by FreneticScribbler** [comment]
Looks good to me on your iPhone Jerbs, until you turn it landscape and then all manner of layout horrors fall out :scream: No idea why the header isn't full width. The rigboard should end where the new button is, as well, it's somehow leaking out of the page layout. Gak. 

Nick, I was gonna guess that you were the one person in the data I pulled that had a weirdly ultra old version of Chrome, but I'm not sure that's allowed in Google Pixel land? If I set my viewport to the size it theoretically is on your phone, it doesn't break, so I'm a little stumped honestly!

**Comment by nickw29** [comment]
Yeah, my phone and browser are up to date.
Mine also looks the same in landscape, maybe it's time for a forum poll

**Comment by nickw29** [comment]
image
This is an interesting look

**Comment by FreneticScribbler** [comment]
Oh dear...

Sent from Proton Mail mobile

-------- Original Message --------

**Comment by FreneticScribbler** [comment]
Should be fixed momentarily. Still can't reproduce any of the other problems on either Firefox or Brave (chromium based) :thinking:

**Pull request merged**
