### PR TITLE
Markdown

### LINKED ISSUE #178: Markdown support
How nice would it be if the description and notes fields had full markdown support, even to the extent of being able to embed images. Thoughts?

### PR DESCRIPTION
**Pull request by tomtom5152**
Adds markdown support to most of the textarea fields.

Provides limited support for paperwork as well.

Would close #178.

### CODE REVIEW

**Comment by davidtaylorhq** [comment]
Since this now has the world of conflicts, I shall close this PR. Shouldn't be a ridiculous amount of work to get it working again if someone is particularly desperate for it.

**Comment by FreneticScribbler** [comment]
Might do this, it would be nice.

**Comment by FreneticScribbler** [comment]
Slightly less super broken...but still super broken :D

**Comment by FreneticScribbler** [comment]
I did indeed do this. Still puzzling on how to test the doowhacker, but otherwise this is ready to go.

**Comment by FreneticScribbler** [comment]
Oh I should investigate strikethrough being broken before I ready-for-review this...

**Comment by FreneticScribbler** [comment]
Should disallow links outside of the notes field and images everywhere too. 

Also look into formatting of horizontal rule. 

Query allowing headers. 

(also format the recent changes doowhacker)

At which point the out of place 'pretty editor' seems pretty surplus bar spell check. Hmm.

Back to the drawing board.

**Comment by FreneticScribbler** [comment]
Apparently closing and reopening the PR will get Heroku to recreate the review app? Let's see

**Comment by FreneticScribbler** [comment]
C'mon Heroku, git on with it

**Comment by FreneticScribbler** [comment]
Well I'm vaguely confident this won't instantly detonate...

**Pull request merged**
