### PR TITLE
Refactor buildsystem to NPM/Gulp, port to BS4 & rewrite RIGS tests accordingly...

### LINKED ISSUE #136: Rig Checklist & Risk Assessment
Originally reported by: **David Taylor (BitBucket: [davidtaylorhq](http://bitbucket.org/davidtaylorhq), GitHub: [davidtaylorhq](http://github.com/davidtaylorhq))**

---

Digitise these. Need to be careful about database structure so data is not lost if form is changed in future

---
- Bitbucket: https://bitbucket.org/nottinghamtec/pyrigs/issue/136

### LINKED ISSUE #162: Recent Changes Cache
Originally reported by: **David Taylor (BitBucket: [davidtaylorhq](http://bitbucket.org/davidtaylorhq), GitHub: [davidtaylorhq](http://github.com/davidtaylorhq))**

---

This takes forever to load sometimes. I spent a while trying to optimise the code when I first made it, so I'm not sure there's much more that can be done on that front. Should be able to cache it, and only regenerate if changes are made.

---
- Bitbucket: https://bitbucket.org/nottinghamtec/pyrigs/issue/163

### LINKED ISSUE #168: Filter Rig Archive
Would be useful to be able to filter the archive to display and count the number of Booked Rigs that were not Dry-hires, for example.

Failing this, an option to hide Cancelled and Non-Rigs, which are generally unnecessary when looking at past rigs.

### LINKED ISSUE #215: JavaScript Dependencies
Are currently a mess. This looks like a pretty tidy, and low effort way to fix it:

https://github.com/nvbn/django-bower

### LINKED ISSUE #322: Event authorisation shows "auth request at" when only updating rig status
It also implies that another email has been sent to the client even though it hasn't.

image

### LINKED ISSUE #391: Linux/Firefox Issues
May also be to do with using Firefox instead of Chrome.

- Access/Meet times I have to manually enter in ISO format, there's no dropdown or the like on those fields for me. 
- Downloading a quote results in a file with no extension that my system still recognises as a PDF but makes Windows very unhappy. 

I'm sure there was more...

### LINKED ISSUE #398: Event duplication should probably set status back to 'Provisional'
Many a time have I duplicated an event and been caught out by the fact it copies event status whereas it clears all other stuff that you might expect. I'm not 100% sold either way though...

### LINKED ISSUE #405: Maybe RIGS shouldn't let you set access times after the event
Per https://rigs.nottinghamtec.co.uk/event/4604/

### LINKED ISSUE #413: Display a list of cables with that type on the cable type detail page
Should be trivial to implement but quite useful in some very specific cases, like the question I had just now...How much 63/3 do we have

### PR DESCRIPTION
**Pull request by FreneticScribbler**
...and some more features along the way. I am the best at scope, the best I say!

Much testing required. No idea if Heroku is even going to be able to spin it...

# New Features
- Digitised Risk Assessments and Event Checklists
	- Not a lot of validation going on here, these are intended to be reviewed by a human, and have a mechanism for doing so that is similar to event approvals
	- However, RIGS will display a confirmation screen when a 'nonstandard' RA is created, asking the user to check with a supervisor/confirm they have done so. It probably needs tweaking to be a bit less annoying...
	- RIGS determines event size automatically when a RA is filled out based on the answers in the power section, then shows the relevant section in subsequent event checklist(s). 
- Dark theme!(!!)
- General rethink of layouts and UX to hopefully make stuff much more clean, readable and consistent. Also should make some little known features more accessible and understandable.
- Search bar now follows you around so it's always in reach. 
- Version history for Invoices/Payments. Also, you should see more stuff show up in the recent changes feed...provided you have the right permissions. 
- Status chips on the rigboard, to help you see an event's overall status at a glance.
- Ctrl-Enter global form submission shortcut 

# Notable Bugs Squashed
- Firefox's *infuriating* lack of support for datetime-local has been fixed with javascript fuckery. No more manually entering ISO format into 'Access at'!
- File naming for paperwork now works more consistently (Technical: Previously, we weren't wrapping the spaces in the file names properly, which made some browsers choke)

# Technical Stuff
- Ported to Bootstrap4 and generally upgraded dependencies across the board
- RIGS tests rewritten from the ground up, coverage now steady at >90%! 
- Better buildsystem that also includes:
	- Browsersync, for automated reloads when changing templates
	- No more bloody compass bodge. Ruby I hate you
	- NPM >.>
- Much much much template deduplication, perhaps too much in places
- Lots of logic that was previously in templates moved up to python level
- User auth and versioning shite separated into (mostly) independent modules, versioning module does some black magic™️ for automatic views. 

Closes #162 
Closes #215 
Closes #136 because I got carried away
Closes #405 
Supersedes and closes #337.
Probably closes #322 
Closes #391 
Closes #398
Closes #413

### CODE REVIEW

**Comment by FreneticScribbler** [comment]
Turned a fix into a feature cause I'm just that good at scope...

**Comment by FreneticScribbler** [comment]
Rigboard doesn't horizontally scroll on mobile... Whoops!

**Comment by josephjboyden** [comment]
- [x] authorized sataus doe not show on rigboard tile once autherized

**Comment by josephjboyden** [comment]
- [x] (sort of) when creating chechlist vehicles will be removed if the checks fail after clicking save, vehicle will reapear once saved succesfuly

**Comment by josephjboyden** [comment]
duplacate events show a autherisation waning despite event not being autherised

**Comment by josephjboyden** [comment]
- [x] rigboard key unclear

**Comment by FreneticScribbler** [comment]
Regression: #326 has been reintroduced

**Comment by FreneticScribbler** [comment]
- [x] Need a 'Large Event' button on the EC that just disables checks. 
- [ ] Optional sharepoint link?

**Comment by FreneticScribbler** [comment]
Need to change DB structure to allow for multiple ECs completed for one event...

**Review by mattysmith22 — COMMENTED** [review]
This is great progress Arona, it has come very far! It adds a lot of new features and is a well-needed refactor.

These are just some thoughts I have:

# UI

1. Why is this all pushed and wrapped to the left? Not big problem, just weird. (on failed logon)
image

2. Is this intentional or just a cool coincidence?
image

3. There is a lot of unused whitespace in desktop mode, may be worth doing main details top left, purchase details top right, then collection and audit below? (view asset)
image

4. This is a common one, might just be BS4. I don’t like the large amount of spacing between items
image
Doesn’t happen when the “Contact details” form entry is empty.
image

5. A lot of the colours are quite high-contrast. This plus the negative space makes it a lot harder to read the text. I know this is BS4 and not you, but it may be beneficial to override that colouring.
image

# Events

6. It might be worth updating generateSampleData so that some things are automatically audited too
image

7. Not sure I am a fan of that green for “New”, but either way it’s fine
image

8. There doesn't seem to be a link to the contact of an event.

9. If the email or phone number for a contact is `None`, it will still try to generate a hyperlink ([tel:None](tel:None)) (Pre-existing, just noticed now)

## Event checklist

10. On mobile, can the checkboxes be made any bigger on the event checklist? If we are hoping to get people to use this on their phones, we should focus on the mobile-friendliness of this content.
image

11. I managed to do this:
image

12. On mobile, the medium power stuff is a bit ... squished. Could you make it so you can scroll it side to side? That seems like it would be more easy to read
image

13. I would recommend setting up the medium power threshold values so they are inside a collapse
https://getbootstrap.com/docs/4.0/components/collapse/

14. This is more of a design and ergonomics thing. Personally, I would recommend allowing for event checklists to be filled in without being complete, and just marking them as so. This allows for an MIC to save repeatedly as they rig the event, and for the MIC and power tech to collaborate on the document. You'd then have 2 layers of validation:

* Layer 1 is just basic form validation (numbers having numbers, foreign key checks etc.) This will fail the form if you submit it
* Layer 2 is actual logic validation of the data in the form, making sure the checklist has been filled in. If this fails, it should still be saved but the checklist should be marked as incomplete / insufficient.

Both ways work, it's just a personal preference.

15. To keep the pattern, the power type checklist should be center-aligned
image

This is what the event creation looks like

image

## Event risk assessment

16) Clicking on the text of an RA item clicks "yes" on the associated radio button
https://streamable.com/zmj3je

## Lists in general

17) I disagree with the showing of database IDs to the end-user. It isn't of any use to them, and is only really for backend stuff (with the exceptions of things that have meaningful IDs like assets.) On the previous version they are there, but easy to miss as they are not emboldened and their column in the table has no identification.
image

This is my first look at the interface! Soon I will be taking a look further into the code, backend and testing.

**Comment by FreneticScribbler** [comment]
```
File "/home/arona/Documents/Github/PyRIGS/versioning/versioning.py", line 28, in display_value
    return [x[1] for x in self.field.choices if x[0] == value][0]
IndexError: list index out of range
```
Hrm

**Comment by FreneticScribbler** [comment]
813b1da also allows the saving of incomplete checklists. No flag yet. 

Still to do:
- [x] Better EC UX on mobile
- [x] Colour palette rework
- [x] Spacing/person link/radio button tweak
- [x] Kill off whitespace

**Comment by FreneticScribbler** [comment]
Should be your feedback largely accounted for @mattysmith22 ... second round please?

image

**Comment by tomtom5152** [comment]
Comments from my initial review, this will be updated later when I’ve got more time to review what’s actually changed on a proper computer

# Critical
## RAs
* barrier/emergency procedures negates the logic of the rest of the questions in that section 
* I feel there should be an acknowledgment screen if there’s anything unusual on the RA to alert to either a mistake or to reinforce it needs checking by a supervisor 
* review screen buttons have some strange wrapping on mobile

## checklist 
* crew record is clunky on mobile and completely broke whilst attempting to submit

# Positives
* feels very clean
* like the new search feature

# Enhancements 
* for the new user, add a mouse over legend for the table row colours somewhere near the bottom out of the way.

**Comment by FreneticScribbler** [comment]
Cheers @tomtom5152 

> barrier/emergency procedures negates the logic of the rest of the questions in that section

Copied directly from the paper list. IIRC its to 'catch out' people who might just be blindly answering yes...

> I feel there should be an acknowledgment screen if there’s anything unusual on the RA to alert to either a mistake or to reinforce it needs checking by a supervisor

This is an excellent idea, I'll do this. Now if only I could find a cleaner way of defining what the 'correct' answer is for each field...any ideas?

> review screen buttons have some strange wrapping on mobile

Yeah that's not ideal is it...good spot

> crew record is clunky on mobile and completely broke whilst attempting to submit

I probably need to check this out on an actual phone, it seems fine in the responsive design tools...

> for the new user, add a mouse over legend for the table row colours somewhere near the bottom out of the way.

Not sure what you mean here? Like the rigboard key?

**Comment by tomtom5152** [comment]
> IIRC its to 'catch out' people who might just be blindly answering yes

This is a terrible reason to keep it that way, especially when it contradicts the help text added above that section which suggests you should answer yes to all questions else speak to a supervisor.

> Now if only I could find a cleaner way of defining what the 'correct' answer is for each field...any ideas?

I've can count about 4 ways of doing that, non of which I particularly like without trying them to see how they work in practice. Perhaps throw an error on the form validation, render the error with an extra checkbox which overrides it, not really sure.

 

> Not sure what you mean here? Like the rigboard key?

Look, just because it's been something that has been complained about since day 1, doesn't mean a full refactor isn't the right time to add one here and to the main rigboard 😛 
Essentially I'm thinking a small link/button at the bottom of the page which opens a popover/modal with a key as to what the background colours mean. Or add a help page describing all the nuances such as the asterisk after a client/venue name etc.

**Comment by FreneticScribbler** [comment]
> This is a terrible reason to keep it that way, especially when it contradicts the help text added above that section which suggests you should answer yes to all questions else speak to a supervisor.

Valid! Personally I agree with you, but I don't want to change the structure vs the paper form without a wider (forum) discussion

> I've can count about 4 ways of doing that, non of which I particularly like without trying them to see how they work in practice. Perhaps throw an error on the form validation, render the error with an extra checkbox which overrides it, not really sure.

I actually meant 'python side' - how best to store what the expected value of each field is. I can't easily make it a property of the fields themselves...

> Essentially I'm thinking a small link/button at the bottom of the page which opens a popover/modal with a key as to what the background colours mean.

So...this already implemented thing??

image

Where else do you want it? :P  

The asterisk is (gradually) being replaced where possible with a linked note icon which should be a lot more self explanatory.

**Comment by FreneticScribbler** [comment]
> On the other hand there is an element of bike shedding inevitable here, so I would suggest just proposing the change and asking for objections rather than trying to make it a discussion.

As if I'm not already versed in how to get decisions out of the forum :D 

> Ah, thats easy. Do a dict of fields with their expected values next to them then iterate through them check each field in turn.

Sounds good :+1: Means I can clean up my kinda dirty tick/cross display filter too

> My eyes must have ceased to function today...

Now you see why I was so confused!

**Comment by FreneticScribbler** [comment]
When you get the chance @mattysmith22 could you look over my changes to versioning as that's the critical blocker to getting this live

**Comment by FreneticScribbler** [comment]
Thoughts on allowing Risk Assessments (and event checklists?) for non events? Thinking mainly for training, and a separate category for training is probably overkill...

**Comment by FreneticScribbler** [comment]
Also allow space on RA for attaching links to rigging and power plans in relevant Sharepoint folders

**Comment by FreneticScribbler** [comment]
If you ignore anything not python and migrations/tests, there's only like 50 files to review @mattysmith22  :P 

https://github.com/nottinghamtec/PyRIGS/pull/412/files?file-filters%5B%5D=.py&w=1

**Pull request merged**
