### PR TITLE
Update CI build version to 3.10

### LINKED ISSUE #597: CI builder python version issue
CI builder fails due to setting up python 3.9 whilst the Pipfile requires 3.10

### PR DESCRIPTION
**Pull request by jb3**
Should fix the CI test image failures.

Closes #597.

### CODE REVIEW

**Comment by jb3** [comment]
We're making progress, but now the test suite seems to just be hanging after `pytest` runs.

**Comment by jb3** [comment]
Passed!

image

I don't see any functionality to trigger a deploy here, does Heroku pick changes up automatically?

The suite just runs tests and calls it quits there.

**Comment by jb3** [comment]
There is a manual deploy job as well which could do something.

If Heroku deployments are failing someone please drop me a copy of the logs (here or joe@jb3.dev if sensitive content) and I'll try see what's happening there.

**Review by nickw29 — APPROVED** [review]
Thanks Joe, Heroku should deploy it automatically I think

**Pull request merged**
