### PR TITLE
Add revision history to invoices & payments

### PR DESCRIPTION
**Pull request by johnathan99j**

### CODE REVIEW

**Comment by tomtom5152** [comment]
@davidtaylorhq any ideas why this isn't creating revisions as it should, I can't see any difference between `Event` and `Invoice` now, but it isn't doing anything at all (including throwing errors) and you know more about the versioning system.

**Comment by davidtaylorhq** [comment]
Don't have time to look at it in detail right now. 

If the issue is that there are no versions being added to the database, I would guess that you need to add some `with reversion.create_revision:` stuff whenever invoices are created/changed.

If the issue is that it's not showing up in the homepage 'activity' thing, then we might need some changes in versioning.py

**Comment by tomtom5152** [comment]
@davidtaylorhq Its the former issue here, I would agree with you and that seems to fix it, however I can't see why its necessary as it isn't used elsewhere which is just confusing.

**Comment by davidtaylorhq** [comment]
I believe reversion patches the built in Django CRUD View classes, hence why we don't need `reversion.create_revision` for most things.

**Comment by mattysmith22** [comment]
The reason why we never need to explicitly state that you want to make a revision usually is because of the revision middleware. Basically, for an entered request, it wraps the entire thing in a `reversion.create_revision`. However, this extra layer does slow things down, so they only do it for things like POSTs and UPDATEs - because who in their right mind would make changes to models on GET right? That is why the creation wasn't being wrapped in a revision, so I just wrapped it manually. I could've configured the middleware so that it did it for all requests, but that would have a performance deficit for all other GETs - better to make an exception to the rule in this case.

Now, from what I can tell the revisioning for payments is working correctly, it just doesn't seem to [follow](https://django-reversion.readthedocs.io/en/release-1.9.3/api.html#following-foreign-key-relationships) correctly. Any ideas on why this is occurring would be greatly appreciated!

Edit: I forgot to mention, I have got it appearing in revisions by forcing it to add the object to the list of objects changed in the revision, but because of the fact that there are no changes to the object, it jut says that nothing significant was changed.

**Comment by FreneticScribbler** [comment]
One of the reasons this behaves unexpectedly is because of the difference between Revision and Version and versioning.py being written to process the latter. 

When you set follow, this is for the Revision rather than the Version, because a Version has a OneToOne relationship with an object. 

So a Revision may contain multiple Versions referring to different objects, which neither our templates nor versioning.py currently account for. Working on it...

**Pull request closed without merging**
