### PR TITLE
Miscellaneous changes/fixes

### PR DESCRIPTION
**Pull request by FreneticScribbler**
PR-ing for staging purposes at this stage. I probably won't squash-merge this given the diversity of the changes.

### CODE REVIEW

**Comment by FreneticScribbler** [comment]
Hmm I've badgered something with my css changes...

**Comment by johnathan99j** [comment]
Wait what, I deployed this?

Doubt...

**Comment by FreneticScribbler** [comment]
> Wait what, I deployed this?
> 
> Doubt...

Both you and David seem to have some sort of auto-deploy shenanigans occurring, its happened a load of times...

**Comment by johnathan99j** [comment]
> Both you and David seem to have some sort of auto-deploy shenanigans occurring, its happened a load of times...

Hmmm, maybe because we both have an account linked to heroku? Paging @davidtaylorhq

**Comment by davidtaylorhq** [comment]
Yeah, it's weird, I think it just picks a random repository contributor with a Heroku account. I don't think it's anything to worry about.

**Comment by johnathan99j** [comment]
> Yeah, it's weird, I think it just picks a random repository contributor with a Heroku account. I don't think it's anything to worry about.

Hmmm, well no harm so whatever I guess 🤷‍♂

**Comment by FreneticScribbler** [comment]
Yeah it's had me do the auto-deploy doodah too so that adds up David.

**Comment by FreneticScribbler** [comment]
The tests that are failing on CI appear to work just fine in my local environment. It must be to do with that CSS change. Any ideas people?

**Comment by FreneticScribbler** [comment]
Aaaaaargh

**Comment by FreneticScribbler** [comment]
Victory..but at what cost...

I've not actually reduced the coverage because that test was just being forced to pass before. A more long term fix is needed, but would be more appropriate in a broader rewrite of testing...

**Comment by FreneticScribbler** [comment]
Standby for rewriting history...naughty I know but I still don't want to squashmerge this in to master and lose the granularity of the range of fixes. I would have kept this all local to make the rewrite less taboo but couldn't have for obvious reasons...

**Review by mattysmith22 — APPROVED** [review]
All looks good!

**Pull request merged**
