### PR TITLE
Reformat all the things

### PR DESCRIPTION
**Pull request by tomtom5152**
Because why wouldn't you want all your code to beautiful (only done in a PR to get a sanity check on Heroku to make sure something isn't borked).
- Python code is now formatted to PEP8
- All other files are defined in .editorconfig as far as possible.

### CODE REVIEW

**Comment by davidtaylorhq** [comment]
Happy for this to be merged since tests pass - there might be some other random spaces pop up in the UI, but shouldn't affect any functionality and I can't be bothered to proof read the entire codebase.

**Comment by tomtom5152** [comment]
@davidtaylorhq I'll have a courtesy glance for them in the most important places, but it is very clever about how it does the formatting so shouldn't be an issue

**Comment by davidtaylorhq** [comment]
screen shot 2016-08-18 at 12 50 43
Just noticed this - spaces in the title

**Comment by tomtom5152** [comment]
@davidtaylorhq well thats just irritating

**Comment by davidtaylorhq** [comment]
So many conflicts, this will have to be done again, bye bye PR

**Pull request closed without merging**
